// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITqGuUTCCj7jCbn-BRmkoBP8T_mHTJGM',
    appId: '1:56189411575:web:3680cb316b51dc99b4b3f2',
    messagingSenderId: '56189411575',
    projectId: 'oturans-f46e2',
    authDomain: 'oturans-f46e2.firebaseapp.com',
    storageBucket: 'oturans-f46e2.firebasestorage.app',
    measurementId: 'G-ZWL19JCNKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFzsyUAuEm17TTL5584_wV11b1TdyAOo',
    appId: '1:198057438508:android:15d499a6f2bf6b53495089',
    messagingSenderId: '198057438508',
    projectId: 'oturans-af119',
    storageBucket: 'oturans-af119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48WFmTDi1UbbMnZI6RUC7bFNkkwRUEwo',
    appId: '1:198057438508:ios:7101b24b30abbc72495089',
    messagingSenderId: '198057438508',
    projectId: 'oturans-af119',
    storageBucket: 'oturans-af119.firebasestorage.app',
    iosBundleId: 'com.example.oturans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMUvs3o7aJmsKs_j49fKwmn-kNxhH58A',
    appId: '1:56189411575:ios:5dd72f62f5fb8d74b4b3f2',
    messagingSenderId: '56189411575',
    projectId: 'oturans-f46e2',
    storageBucket: 'oturans-f46e2.firebasestorage.app',
    iosBundleId: 'com.example.oturans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITqGuUTCCj7jCbn-BRmkoBP8T_mHTJGM',
    appId: '1:56189411575:web:38b784c66d2b3596b4b3f2',
    messagingSenderId: '56189411575',
    projectId: 'oturans-f46e2',
    authDomain: 'oturans-f46e2.firebaseapp.com',
    storageBucket: 'oturans-f46e2.firebasestorage.app',
    measurementId: 'G-7H65R3D161',
  );
}